### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by prateekjahead** [spdy-http2/spdy-transport#59]
Running into this error when starting my express server:

```
node_modules/spdy-transport/lib/spdy-transport/priority.js:81
PriorityNode.prototype.removeChildren = function removeChildren () {
^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```
Not able to resolve it.

**Comment by Mydayyy** [comment]
Running into the same error right now. Did you discover any solution?

**Comment by JoeBassanova** [comment]
This Error is caused by an mistakenly commented out line in:
node_modules/spdy-transport/lib/spdy-transport/priority.js

Line 71:
PriorityNode.prototype.removeChild = function removeChild (child) {
  this.children.weight -= child.weight
  var index = utils.binarySearch(this.children.list, child, compareChildren)
/*
  if (index !== -1 && this.children.list.length >= index) {
*/
    this.children.list.splice(index, 1)
  }
}

**Comment by Mydayyy** [comment]
You all probably followed this guide and forgot about it. Congratulations!: https://github.com/spdy-http2/spdy-transport/issues/47#issuecomment-369020176

**Comment by prateekjahead** [comment]
As critically explained by @Mydayyy, removing the `quickFix` mentioned in [this comment](https://github.com/spdy-http2/spdy-transport/issues/47#issuecomment-369020176) did the job! Thanks all! 😅
